# Generated by Django 2.2.5 on 2019-09-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('discount_type', models.CharField(choices=[('%', '$')], max_length=1)),
                ('discount_value', models.IntegerField()),
                ('active_timestamp', models.DateTimeField()),
                ('expiry_timestamp', models.DateTimeField()),
            ],
        ),
    ]
