# Generated by Django 2.2.5 on 2019-09-25 07:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import vouchers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{10}$', code='invalid_code', message='Space is not allow and Length has to be 10')])),
                ('discount_type', models.CharField(choices=[('%', '%'), ('$', '$')], max_length=1)),
                ('discount_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('eligible_type', vouchers.models.PatchedMultiSelectField(choices=[(1, 'PRODUCT'), (2, 'TREATMENT')], max_length=3)),
                ('copied', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('active_timestamp', models.DateTimeField()),
                ('expiry_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Redeem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeem_timestamp', models.DateTimeField()),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.Item')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.Voucher')),
            ],
        ),
    ]
