# Generated by Django 2.2.5 on 2019-09-24 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='copied',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$', code='invalid_code', message='Space is not allow')]),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('%', '%'), ('$', '$')], max_length=1),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_value',
            field=models.PositiveIntegerField(),
        ),
    ]
