# Generated by Django 2.2.5 on 2019-09-24 06:15

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20190924_0146'),
        ('vouchers', '0002_auto_20190924_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='eligible_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'PRODUCT'), (2, 'TREATMENT')], default=3, max_length=3),
        ),
        migrations.CreateModel(
            name='Redeem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeem_timestamp', models.DateTimeField()),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.Item')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.Voucher')),
            ],
        ),
    ]
