# Generated by Django 2.2.5 on 2019-09-24 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_auto_20190924_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='discount_value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
