# Generated by Django 2.2.5 on 2019-09-24 18:52

import django.core.validators
from django.db import migrations, models
import vouchers.models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0004_auto_20190924_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{10}$', code='invalid_code', message='Space is not allow and Length has to be 10')]),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='eligible_type',
            field=vouchers.models.PatchedMultiSelectField(choices=[(1, 'PRODUCT'), (2, 'TREATMENT')], max_length=3),
        ),
    ]
