# Generated by Django 2.2.5 on 2019-09-25 07:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$', code='invalid_sku', message='Space is not allow')])),
                ('name', models.CharField(max_length=25, unique=True)),
                ('item_type', models.IntegerField(choices=[(1, 'PRODUCT'), (2, 'TREATMENT')])),
                ('status', models.BooleanField(default=True)),
                ('active_timestamp', models.DateTimeField()),
                ('expiry_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('effective_timestamp', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
            ],
        ),
    ]
