# Generated by Django 2.2.8 on 2019-12-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_hash',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
