# Generated by Django 2.2.5 on 2019-09-23 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20190924_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.IntegerField(choices=[(1, 'PRODUCT'), (2, 'TREATMENT')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[^\\S]+$', code='invalid_sku', message='Space is not allow')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.BooleanField(),
        ),
    ]
