# Generated by Django 2.2.5 on 2019-09-23 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20190924_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$', code='invalid_sku', message='Space is not allow')]),
        ),
    ]
